// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CounterAnimalsController from "./counter_animals_controller"
application.register("counter-animals", CounterAnimalsController)

import DonutController from "./donut_controller"
application.register("donut", DonutController)

import DonuttwoController from "./donuttwo_controller"
application.register("donuttwo", DonuttwoController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)
